networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/dynamic/:/etc/traefik/dynamic:ro
      - ./ssl/:/etc/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  static-pages:
    image: nginx:latest
    volumes:
      - ./data/pages/:/usr/share/nginx/html
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  canary-cd:
    image: ghcr.io/rehborn/canary-cd:0.1.dev3
    volumes:
      - ./data/:/data/
      - /root/.docker/config.json:/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SALT: ${CANARY_SALT}
    networks:
      - traefik
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.canary-cd.rule: Host(`${CANARY_HOST}`)
      traefik.http.routers.canary-cd.entrypoints: tls
      traefik.http.routers.canary-cd.tls: true
      traefik.http.routers.canary-cd.tls.certresolver: letsencrypt
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
